import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import '@/src/styles/variables.css';
import '@/src/styles/global.scss';

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} font-sans antialiased`}
        style={{
          fontFamily: `"Space Grotesk", system-ui, sans-serif`,
        }}
      >
        {children}
      </body>
    </html>
  );
}
